# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 01:53
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examPaperQuestion', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=b'')),
                ('examPaperAnswers', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/uploads/examPaperAnswers'), upload_to=b'')),
                ('examPaperReport', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/uploads/examPaperReports'), upload_to=b'')),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3')], max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('FORWARDED', 'Forwarded'), ('APPROVED', 'Approved')], max_length=10)),
                ('notes', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipExamUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('examPaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_paper.ExamPaper')),
                ('externalExaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tertiary', to='accs.UserProfile')),
                ('firstExaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='accs.UserProfile')),
                ('secondExaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='accs.UserProfile')),
            ],
        ),
    ]
