# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 02:11
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0002_auto_20170827_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='examPaperAnswers',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/media/examPaperAnswers'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='examPaperQuestion',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/media/examPaperQuestions'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='examPaperReport',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/media/examPaperReports'), upload_to=b''),
        ),
    ]
