# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0005_auto_20170827_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=10)),
                ('courseName', models.CharField(max_length=30)),
                ('faculty', models.CharField(choices=[('Faculty of Science and Technology', 'FST'), ('Faculty of Engineering', 'FE'), ('Faculty of Food and Agriculture', 'FFA')], max_length=30)),
            ],
        ),
    ]
