# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0006_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('FACULTY OF SCIENCE AND TECHNOLOGY', 'Faculty of Science and Technology'), ('FACULTY OF ENGINEERING', 'Faculty of Engineering'), ('FACULTY OF FOOD AND AGRICULTURE', 'Faculty of Food and Agriculture')], max_length=30),
        ),
    ]
