# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0009_exampaper_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_paper.Course'),
        ),
    ]
