# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 00:55
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_paper', '0010_auto_20170906_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCode',
            field=models.CharField(max_length=10, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='examPaperAnswers',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='examPaperQuestion',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='examPaperReport',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=b''),
        ),
    ]
